# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib_list = [1,1]

for i in range(31):
    fib_list.append(fib_list[-1] + fib_list[-2])

sum_evens = 0

for number in fib_list:
    if number % 2 == 0:
        sum_evens += number

print(sum_evens)